spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangjuns8/spring-cloud-study
          search-paths: properties
          username:
          password:
      label: master

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true #将IP注册到Eureka Server上，而如果不配置就是机器的主机名
