server:
  port: 8030

spring:
  application:
    name: microservice-consumer-movie-feign-with-hystrix

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

feign:
  hystrix:
    #开启feign的hystrix支持,默认是false
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream