

server:
  port: 8084

spring:
  application:
    name: microservice-provider-user

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #注册到刚才那台Eureka Server地址


#eureka:
#  instance:
#    #eureka客户端的实例名字（主机名）
#    hostname: provider-user
#  client:
#    service-url:
#      #表示向注册中心注册自己
#      register-with-eureka: true
#      #表示需要去注册中心检索服务
#      fetch-registry: true
#      #与eureka server交互的地址，包括查询服务和注册服务
#      defaultZone: http://localhost:8761/eureka