

server:
  port: 8080

spring:
  application:
    name: wjtest-javaweb-cboot
  freemarker:
    cache: false #关闭模板缓存，方便测试
    settings:
      template_update_delay: 0 #检查模板更新延迟时间，设置为0表示立即检查，如果时间大于0会有缓存不方便进行模板测试
    charset: UTF-8
    check-template-location: true
    suffix: .ftl
    template-loader-path: classpath:/templates
    request-context-attribute: request

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #注册到刚才那台Eureka Server地址
  instance:
    preferIpAddress: true #将IP注册到Eureka Server上，而如果不配置就是机器的主机名

user: Evan