
spring:
  application:
    name: microservice-config-client
  cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled: true
        service-id: microservice-config-server
#      uri: http://localhost:8888/ #如果使用discovery，读取配置文件不再写ip地址，而是服务名，这时如果配置服务部署多份，通过负载均衡，从而高可用。
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8882

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true #将IP注册到Eureka Server上，而如果不配置就是机器的主机名



management:
#  endpoint:
#    bus:
#      enabled: true
  endpoints:
    web:
      exposure:
        include: bus-refresh
#management:
#  security:
#    enabled=false