spring:
  application:
    name: microservice-api-gateway

server:
  port: 8050

eureka:
  instance:
    #hostname: gateway
    hostname: CDC112057
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      #如果是多eureka：
      #defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/

zuul:
#  ignored-services: microservice-provider-user                        # 需要忽视的服务(配置后将不会被路由)
  routes:
    movie:                                                            # 可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
      path: /movie/**                                                 # 想要映射到的路径
      service-id: microservice-consumer-movie-feign-with-hystrix     # Eureka中的serviceId
    user:                                                            # 可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
      path: /user/**                                                 # 想要映射到的路径
      service-id: microservice-provider-user                         # Eureka中的serviceId
